### ISSUE TITLE
Custom deadzone shapes.

### ISSUE THREAD

**Issue by Cybereu** [matlo/GIMX#395] opened 2016-09-03 00:14 UTC
At the moment there are 2 deadzone shapes, they cover almost every game but there are a lot AAA games that dont use square or elipse shape as showed here: 
https://drive.google.com/drive/mobile/folders/0B3jq3Adc2gXiRExmcncyQ0ZUYXEtOGNwTmxJcm9yUQ

Improvement: Custom shape on given formula by user.

**Comment by matlo** [comment] 2016-09-07 07:36
This is similar to #143.

I think the dead zone calibration mode could be improved to produce the exact dead zone shape.
And the exact dead zone shape could be embedded into the configuration file.

**Comment by matlo** [comment] 2018-01-10 20:54
Duplicate of #143.

**Closed by matlo** 2018-01-10 20:54 UTC
